version: 2
updates:
- package-ecosystem: gradle
  directory: "/buildSrc"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - MrBean355
  assignees:
  - MrBean355
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.4.2"
  - dependency-name: software.amazon.awssdk:bom
    versions:
    - "> 2.16.8, < 2.17"
  - dependency-name: software.amazon.awssdk:bom
    versions:
    - 2.15.82
    - 2.16.0
    - 2.16.2
    - 2.16.3
    - 2.16.5
    - 2.16.6
    - 2.16.7
