name: Automated release

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vpk

      - name: Repackage mods
        run: |
          chmod +x gradlew
          ./gradlew buildMod -Pcompiler.fullCompile=false

      - name: Upload mods to S3
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TARGET_ROONS_ENV: prod
        run: |
          ./gradlew publishMod

      - name: Commit & push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'mrbean355@users.noreply.github.com'
          git commit -am "Add the latest strings files" || true
          git push