name: Build project

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vpk

      - name: Repack mods
        run: |
          chmod +x gradlew
          ./gradlew buildMod -Pcompiler.fullCompile=false
