name: Publish on push to main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vpk

      - name: Repackage mods
        run: |
          chmod +x gradlew
          ./gradlew buildMod -Pcompiler.fullCompile=false

      - name: Upload mods to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TARGET_ROONS_ENV: prod
        run: |
          ./gradlew publishMod -Ptelegram.sendMessage=false

      - name: Commit & push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'mrbean355@users.noreply.github.com'
          git commit -am "Add the latest strings files" || true
          git push
